### ISSUE TITLE
Integrate other Firebase tools

### ISSUE THREAD

**Issue by igorsantos07** [igorsantos07/clockify-targets#36]
- [ ] ~Crashlytics~ actually that's for native apps only?? lol
- [x] Analytics - moved to #35
- [ ] performance monitoring - moved to #35
- [ ] [AppCheck (reCAPTCHA)](https://firebase.google.com/docs/app-check/web/recaptcha-enterprise-provider?authuser=0)  - moved to #35
- [ ] Database - #9
- [x] Hosting - #35
